search:
  job_title: Financial Analyst
target_skills:
- Python
- SQL
- Tableau
- Power BI
- Excel
- Communication
- Project Management
- Leadership
- AWS
- Azure
- Snowflake
- R
- Statistics
- Customer Service
- Sales
- Marketing
