search:
  job_title: Data Engineer
target_skills:
- Python
- SQL
- Tableau
- Power BI
- Excel
- R
- SAS
- AWS
- Azure
- GCP
- Spark
- Airflow
- Snowflake
- Looker
- dbt
- Docker
- Kubernetes
- Java
- Scala
- NoSQL
- Hadoop
