"""
Train a small TF-IDF + logistic model to label phrases as hard / soft / non_relevant.

Uses bundled seed labels so the project stays self-contained (no external API calls).
Fallback is handled in phrase_labels when prediction is unavailable.
"""

from __future__ import annotations

from functools import lru_cache
from typing import Literal

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

SkillTriple = Literal["hard", "soft", "non_relevant"]

# Seed examples: phrase text as produced by TF-IDF + title-case formatting (see skill_analyzer._format_phrase).
_SEED: list[tuple[str, SkillTriple]] = [
    # --- Non-relevant: recruiting boilerplate & ultra-generic nouns ---
    ("experience", "non_relevant"),
    ("years experience", "non_relevant"),
    ("year experience", "non_relevant"),
    ("work experience", "non_relevant"),
    ("professional experience", "non_relevant"),
    ("relevant experience", "non_relevant"),
    ("prior experience", "non_relevant"),
    ("industry experience", "non_relevant"),
    ("insurance", "non_relevant"),
    ("insurance industry", "non_relevant"),
    ("enterprise", "non_relevant"),
    ("enterprise architecture", "hard"),
    ("technology", "non_relevant"),
    ("business", "non_relevant"),
    ("company", "non_relevant"),
    ("organization", "non_relevant"),
    ("team", "non_relevant"),
    ("environment", "non_relevant"),
    ("role", "non_relevant"),
    ("position", "non_relevant"),
    ("opportunity", "non_relevant"),
    ("career", "non_relevant"),
    ("salary", "non_relevant"),
    ("benefits", "non_relevant"),
    ("remote", "non_relevant"),
    ("hybrid", "non_relevant"),
    ("full time", "non_relevant"),
    ("part time", "non_relevant"),
    ("location", "non_relevant"),
    ("states", "non_relevant"),
    ("national", "non_relevant"),
    ("global", "non_relevant"),
    ("dynamic", "non_relevant"),
    ("fast paced", "non_relevant"),
    ("fast paced environment", "non_relevant"),
    ("growing", "non_relevant"),
    ("growing team", "non_relevant"),
    ("equal opportunity", "non_relevant"),
    ("drug screen", "non_relevant"),
    ("background check", "non_relevant"),
    ("clearance", "non_relevant"),
    ("relocation", "non_relevant"),
    ("travel", "non_relevant"),
    ("pay", "non_relevant"),
    ("compensation", "non_relevant"),
    ("bonus", "non_relevant"),
    ("package", "non_relevant"),
    ("description", "non_relevant"),
    ("requirements", "non_relevant"),
    ("qualifications", "non_relevant"),
    ("preferred", "non_relevant"),
    ("minimum", "non_relevant"),
    ("plus", "non_relevant"),
    ("must", "non_relevant"),
    ("ability", "non_relevant"),
    ("skills", "non_relevant"),
    ("knowledge", "non_relevant"),
    ("understanding", "non_relevant"),
    ("familiarity", "non_relevant"),
    ("degree", "non_relevant"),
    ("bachelor", "non_relevant"),
    ("master", "non_relevant"),
    ("certification", "non_relevant"),
    ("license", "non_relevant"),
    ("candidate", "non_relevant"),
    ("applicant", "non_relevant"),
    ("employee", "non_relevant"),
    ("employer", "non_relevant"),
    ("client", "non_relevant"),
    ("customer", "non_relevant"),
    ("accounts", "non_relevant"),
    ("sales", "non_relevant"),
    ("marketing", "non_relevant"),
    ("operations", "non_relevant"),
    ("services", "non_relevant"),
    ("solutions", "non_relevant"),
    ("products", "non_relevant"),
    ("projects", "non_relevant"),
    ("process", "non_relevant"),
    ("processes", "non_relevant"),
    ("support", "non_relevant"),
    ("delivery", "non_relevant"),
    ("management", "non_relevant"),
    ("leadership", "soft"),
    ("development", "non_relevant"),
    ("growth", "non_relevant"),
    ("opportunities", "non_relevant"),
    ("success", "non_relevant"),
    ("goals", "non_relevant"),
    ("mission", "non_relevant"),
    ("culture", "non_relevant"),
    ("values", "non_relevant"),
    ("diversity", "non_relevant"),
    ("inclusion", "non_relevant"),
    ("eeo", "non_relevant"),
    ("veteran", "non_relevant"),
    ("disability", "non_relevant"),
    ("status", "non_relevant"),
    ("authorized", "non_relevant"),
    ("sponsorship", "non_relevant"),
    # --- Soft skills ---
    ("communication", "soft"),
    ("communication skills", "soft"),
    ("written communication", "soft"),
    ("verbal communication", "soft"),
    ("leadership skills", "soft"),
    ("teamwork", "soft"),
    ("collaboration", "soft"),
    ("collaborative", "soft"),
    ("interpersonal", "soft"),
    ("interpersonal skills", "soft"),
    ("stakeholder", "soft"),
    ("stakeholder management", "soft"),
    ("negotiation", "soft"),
    ("presentation", "soft"),
    ("presentation skills", "soft"),
    ("facilitation", "soft"),
    ("mentoring", "soft"),
    ("coaching", "soft"),
    ("empathy", "soft"),
    ("adaptability", "soft"),
    ("problem solving", "soft"),
    ("critical thinking", "soft"),
    ("time management", "soft"),
    ("attention detail", "soft"),
    ("detail oriented", "soft"),
    ("customer service", "soft"),
    ("conflict resolution", "soft"),
    ("emotional intelligence", "soft"),
    ("active listening", "soft"),
    ("public speaking", "soft"),
    ("relationship building", "soft"),
    ("cross functional", "soft"),
    ("organizational skills", "soft"),
    ("prioritization", "soft"),
    ("multitasking", "soft"),
    ("accountability", "soft"),
    ("initiative", "soft"),
    ("resilience", "soft"),
    ("influence", "soft"),
    ("persuasion", "soft"),
    ("diplomacy", "soft"),
    ("listening skills", "soft"),
    ("writing skills", "soft"),
    ("people skills", "soft"),
    ("executive presence", "soft"),
    # --- Hard skills / tools / methods ---
    ("python", "hard"),
    ("sql", "hard"),
    ("excel", "hard"),
    ("microsoft excel", "hard"),
    ("power bi", "hard"),
    ("tableau", "hard"),
    ("looker", "hard"),
    ("snowflake", "hard"),
    ("aws", "hard"),
    ("azure", "hard"),
    ("gcp", "hard"),
    ("kubernetes", "hard"),
    ("docker", "hard"),
    ("linux", "hard"),
    ("windows", "hard"),
    ("javascript", "hard"),
    ("typescript", "hard"),
    ("react", "hard"),
    ("node", "hard"),
    ("java", "hard"),
    ("scala", "hard"),
    ("spark", "hard"),
    ("hadoop", "hard"),
    ("airflow", "hard"),
    ("dbt", "hard"),
    ("etl", "hard"),
    ("api", "hard"),
    ("rest api", "hard"),
    ("graphql", "hard"),
    ("machine learning", "hard"),
    ("deep learning", "hard"),
    ("nlp", "hard"),
    ("statistics", "hard"),
    ("a/b testing", "hard"),
    ("experimentation", "hard"),
    ("data modeling", "hard"),
    ("data analysis", "hard"),
    ("analysis", "hard"),
    ("statistical analysis", "hard"),
    ("data engineering", "hard"),
    ("analytics", "hard"),
    ("predictive modeling", "hard"),
    ("regression", "hard"),
    ("classification", "hard"),
    ("forecasting", "hard"),
    ("reporting", "hard"),
    ("dashboards", "hard"),
    ("kpi", "hard"),
    ("metrics", "hard"),
    ("visualization", "hard"),
    ("pandas", "hard"),
    ("numpy", "hard"),
    ("scikit learn", "hard"),
    ("tensorflow", "hard"),
    ("pytorch", "hard"),
    ("git", "hard"),
    ("ci/cd", "hard"),
    ("jenkins", "hard"),
    ("agile", "hard"),
    ("scrum", "hard"),
    ("jira", "hard"),
    ("confluence", "hard"),
    ("saas", "hard"),
    ("salesforce", "hard"),
    ("sap", "hard"),
    ("workday", "hard"),
    ("gaap", "hard"),
    ("sox", "hard"),
    ("gdpr", "hard"),
    ("hipaa", "hard"),
    ("pci", "hard"),
    ("risk management", "hard"),
    ("compliance", "hard"),
    ("internal controls", "hard"),
    ("financial modeling", "hard"),
    ("underwriting", "hard"),
    ("claims", "hard"),
    ("actuarial", "hard"),
    ("policy", "hard"),
    ("litigation", "hard"),
    ("contract review", "hard"),
    ("due diligence", "hard"),
    ("business analysis", "hard"),
    ("product management", "hard"),
    ("project management", "hard"),
    ("people management", "soft"),
    ("requirements gathering", "hard"),
    ("process improvement", "hard"),
    ("six sigma", "hard"),
    ("lean", "hard"),
    ("sql server", "hard"),
    ("postgresql", "hard"),
    ("mysql", "hard"),
    ("oracle", "hard"),
    ("mongodb", "hard"),
]


def _build_pipeline() -> Pipeline:
    phrases, labels = zip(*_SEED)
    pipe: Pipeline = Pipeline(
        [
            (
                "tfidf",
                TfidfVectorizer(
                    lowercase=True,
                    ngram_range=(1, 2),
                    min_df=1,
                    sublinear_tf=True,
                    max_features=8000,
                ),
            ),
            (
                "clf",
                LogisticRegression(
                    max_iter=2500,
                    class_weight="balanced",
                    solver="lbfgs",
                    random_state=42,
                ),
            ),
        ]
    )
    pipe.fit(phrases, labels)
    return pipe


@lru_cache(maxsize=1)
def _model() -> Pipeline:
    return _build_pipeline()


def predict_skill_label(phrase: str) -> SkillTriple:
    """Return ML label for a phrase (same casing as stored in found_skills)."""
    p = (phrase or "").strip()
    if not p:
        return "non_relevant"
    lab = _model().predict([p])[0]
    if lab not in ("hard", "soft", "non_relevant"):
        return "non_relevant"
    return lab  # type: ignore[return-value]
